name: NASA CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: npm init
        run: npm init -y
      - run: npm install
      - name: npm install in client
        run: npm install --prefix client
      - run: npm run build --prefix client